import type { Item } from './index'
import { daysFromNow, isoFrom } from './utils/time'

const MINUTE = 60_000
const HOUR = 60 * MINUTE
const DAY = 24 * HOUR

function make(overrides: Partial<Item> & Pick<Item, 'id' | 'title' | 'type'>): Item {
  return {
    status: 'inbox',
    body: null,
    url: null,
    dueAt: null,
    reminderAt: null,
    priority: null,
    tags: [],
    doneAt: null,
    createdAt: isoFrom(0),
    updatedAt: isoFrom(0),
    ...overrides,
  }
}

export function createMockItems(): Item[] {
  return [
    // Inbox — unprocessed captures, mixed types
    make({
      id: 'inbox-m22',
      type: 'task',
      title: 'Need to finish M22 review',
      body: 'Go through the M22 review notes before the sync.',
      priority: 'high',
      dueAt: isoFrom(2 * HOUR),
      createdAt: isoFrom(-30 * MINUTE),
      updatedAt: isoFrom(-30 * MINUTE),
      tags: ['work'],
    }),
    make({
      id: 'inbox-docker',
      type: 'learning',
      title: 'Learn Docker networking',
      body: 'Bridge networks, DNS, ports and compose networking.',
      url: 'https://docs.docker.com/network/',
      priority: 'medium',
      createdAt: isoFrom(-1 * DAY),
      updatedAt: isoFrom(-1 * DAY),
    }),
    make({
      id: 'inbox-ai-assistant',
      type: 'idea',
      title: 'Interesting idea: personal AI coding assistant',
      body: 'A local assistant that knows my codebase conventions and runs offline.',
      priority: 'medium',
      createdAt: isoFrom(-3 * HOUR),
      updatedAt: isoFrom(-3 * HOUR),
    }),
    make({
      id: 'inbox-rahul',
      type: 'task',
      title: 'Ask Rahul about the API issue',
      body: 'The 500 on GET /items — does it reproduce on his machine?',
      priority: 'medium',
      createdAt: isoFrom(-5 * HOUR),
      updatedAt: isoFrom(-5 * HOUR),
    }),
    make({
      id: 'inbox-rag',
      type: 'link',
      title: 'Read this article about RAG',
      body: 'A practical guide to retrieval-augmented generation.',
      url: 'https://example.com/a-practical-guide-to-rag',
      createdAt: isoFrom(-2 * DAY),
      updatedAt: isoFrom(-2 * DAY),
    }),
    make({
      id: 'inbox-laptop-stand',
      type: 'task',
      title: 'Buy a laptop stand',
      priority: 'low',
      createdAt: isoFrom(-6 * HOUR),
      updatedAt: isoFrom(-6 * HOUR),
    }),
    make({
      id: 'inbox-call-mom',
      type: 'note',
      title: 'Call mom on Sunday',
      body: 'Evening, after dinner.',
      createdAt: isoFrom(-1 * DAY),
      updatedAt: isoFrom(-1 * DAY),
    }),
    make({
      id: 'inbox-garden',
      type: 'idea',
      title: 'Plan the garden redesign',
      body: 'Herbs along the south wall, tomatoes in the raised bed.',
      priority: 'low',
      createdAt: isoFrom(-2 * DAY),
      updatedAt: isoFrom(-2 * DAY),
    }),
    make({
      id: 'inbox-backups',
      type: 'task',
      title: 'Set up backups for photos',
      priority: 'high',
      dueAt: daysFromNow(3),
      createdAt: isoFrom(-1 * DAY),
      updatedAt: isoFrom(-1 * DAY),
    }),
    make({
      id: 'inbox-embeddings-video',
      type: 'learning',
      title: 'Watch a video on vector embeddings',
      priority: 'medium',
      createdAt: isoFrom(-4 * HOUR),
      updatedAt: isoFrom(-4 * HOUR),
    }),
    make({
      id: 'inbox-sysdesign-article',
      type: 'link',
      title: 'Read the system design primer',
      url: 'https://example.com/system-design-primer',
      createdAt: isoFrom(-5 * DAY),
      updatedAt: isoFrom(-5 * DAY),
    }),
    make({
      id: 'inbox-pricing',
      type: 'idea',
      title: 'Think about pricing for the side project',
      priority: 'low',
      createdAt: isoFrom(-3 * DAY),
      updatedAt: isoFrom(-3 * DAY),
    }),

    // Tasks
    make({
      id: 'task-expense',
      type: 'task',
      status: 'active',
      title: 'Submit expense report',
      priority: 'medium',
      dueAt: daysFromNow(0),
      createdAt: isoFrom(-2 * DAY),
      updatedAt: isoFrom(-2 * DAY),
      tags: ['work'],
    }),
    make({
      id: 'task-dentist',
      type: 'task',
      status: 'active',
      title: 'Book dentist appointment',
      priority: 'high',
      dueAt: daysFromNow(-2),
      createdAt: isoFrom(-6 * DAY),
      updatedAt: isoFrom(-6 * DAY),
    }),
    make({
      id: 'task-plants',
      type: 'task',
      status: 'active',
      title: 'Water the plants',
      priority: 'low',
      dueAt: daysFromNow(0),
      createdAt: isoFrom(-1 * DAY),
      updatedAt: isoFrom(-1 * DAY),
    }),
    make({
      id: 'task-prs',
      type: 'task',
      status: 'active',
      title: 'Review open PRs',
      priority: 'high',
      dueAt: daysFromNow(1),
      createdAt: isoFrom(-8 * HOUR),
      updatedAt: isoFrom(-8 * HOUR),
      tags: ['work'],
    }),
    make({
      id: 'task-domain',
      type: 'task',
      status: 'active',
      title: 'Renew domain',
      priority: 'medium',
      dueAt: daysFromNow(5),
      createdAt: isoFrom(-3 * DAY),
      updatedAt: isoFrom(-3 * DAY),
    }),
    make({
      id: 'task-passport',
      type: 'task',
      status: 'active',
      title: 'Renew passport',
      priority: 'medium',
      dueAt: daysFromNow(10),
      createdAt: isoFrom(-4 * DAY),
      updatedAt: isoFrom(-4 * DAY),
    }),
    make({
      id: 'task-tax',
      type: 'task',
      status: 'active',
      title: 'Prep quarterly tax estimates',
      priority: 'medium',
      dueAt: daysFromNow(14),
      createdAt: isoFrom(-2 * DAY),
      updatedAt: isoFrom(-2 * DAY),
    }),
    make({
      id: 'task-hike',
      type: 'task',
      status: 'active',
      title: 'Plan weekend hike',
      priority: 'low',
      createdAt: isoFrom(-1 * DAY),
      updatedAt: isoFrom(-1 * DAY),
    }),
    make({
      id: 'task-electricity',
      type: 'task',
      status: 'active',
      title: 'Pay electricity bill',
      priority: 'high',
      dueAt: daysFromNow(-1),
      createdAt: isoFrom(-2 * DAY),
      updatedAt: isoFrom(-2 * DAY),
    }),
    make({
      id: 'task-phoenix',
      type: 'task',
      status: 'done',
      title: 'Finish reading The Phoenix Project',
      priority: 'low',
      createdAt: isoFrom(-9 * DAY),
      updatedAt: isoFrom(-2 * DAY),
      doneAt: isoFrom(-2 * DAY),
    }),
    make({
      id: 'task-shoes',
      type: 'task',
      status: 'done',
      title: 'Order new running shoes',
      priority: 'low',
      createdAt: isoFrom(-3 * DAY),
      updatedAt: isoFrom(-4 * HOUR),
      doneAt: isoFrom(-4 * HOUR),
    }),

    // Notes
    make({
      id: 'note-reading-list',
      type: 'note',
      status: 'active',
      title: 'Reading list',
      body: 'Atomic Habits, Deep Work, The Phoenix Project.',
      createdAt: isoFrom(-7 * DAY),
      updatedAt: isoFrom(-2 * DAY),
    }),
    make({
      id: 'note-standup',
      type: 'note',
      status: 'active',
      title: 'Talk notes from standup',
      body: 'Shipped parser v2. Alex blocked on registry access.',
      createdAt: isoFrom(-1 * DAY),
      updatedAt: isoFrom(-5 * HOUR),
      tags: ['work'],
    }),
    make({
      id: 'note-deep-work',
      type: 'note',
      status: 'active',
      title: 'Book notes — Deep Work',
      body: 'Schedule deep work blocks before noon. Email is not urgent.',
      createdAt: isoFrom(-12 * DAY),
      updatedAt: isoFrom(-3 * DAY),
    }),

    // Ideas
    make({
      id: 'idea-finance',
      type: 'idea',
      status: 'active',
      title: 'Build a personal finance tracker',
      body: 'Pull transactions, tag them automatically, surface a weekly summary.',
      createdAt: isoFrom(-5 * DAY),
      updatedAt: isoFrom(-5 * DAY),
    }),
    make({
      id: 'idea-code-review',
      type: 'idea',
      status: 'active',
      title: 'AI code review assistant',
      body: 'Runs on every PR, knows our conventions.',
      createdAt: isoFrom(-4 * DAY),
      updatedAt: isoFrom(-4 * DAY),
    }),
    make({
      id: 'idea-meeting-tasks',
      type: 'idea',
      status: 'active',
      title: 'Automatic meeting-to-task system',
      body: 'Transcript → follow-ups → tasks with owners.',
      createdAt: isoFrom(-2 * DAY),
      updatedAt: isoFrom(-2 * DAY),
    }),

    // Learning backlog
    make({
      id: 'learn-docker',
      type: 'learning',
      status: 'active',
      title: 'Docker',
      body: 'Networking, volumes, compose.',
      url: 'https://docs.docker.com/',
      priority: 'medium',
      createdAt: isoFrom(-10 * DAY),
      updatedAt: isoFrom(-1 * DAY),
    }),
    make({
      id: 'learn-rag',
      type: 'learning',
      status: 'active',
      title: 'RAG',
      body: 'Retrieval, chunking, reranking.',
      url: 'https://example.com/rag',
      priority: 'high',
      createdAt: isoFrom(-8 * DAY),
      updatedAt: isoFrom(-2 * DAY),
    }),
    make({
      id: 'learn-embeddings',
      type: 'learning',
      status: 'inbox',
      title: 'Embeddings',
      priority: 'medium',
      createdAt: isoFrom(-6 * DAY),
      updatedAt: isoFrom(-6 * DAY),
    }),
    make({
      id: 'learn-kubernetes',
      type: 'learning',
      status: 'inbox',
      title: 'Kubernetes',
      priority: 'low',
      createdAt: isoFrom(-9 * DAY),
      updatedAt: isoFrom(-9 * DAY),
    }),
    make({
      id: 'learn-system-design',
      type: 'learning',
      status: 'active',
      title: 'System Design',
      body: 'Load balancers, caching, queues, databases.',
      priority: 'high',
      createdAt: isoFrom(-14 * DAY),
      updatedAt: isoFrom(-3 * DAY),
    }),
    make({
      id: 'learn-async-python',
      type: 'learning',
      status: 'inbox',
      title: 'Async Python',
      priority: 'low',
      createdAt: isoFrom(-7 * DAY),
      updatedAt: isoFrom(-7 * DAY),
    }),
  ]
}
